---
title: "GOC Atlantis regionalization"
output: html_notebook
---

```{r setup}
library("magrittr")
devtools::load_all()
```


Main fishery communities from Paez-Osuna et al. (2016) 
```{r map_communities, include=FALSE}
googlesheets4::gs4_deauth()

coms.fish <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1qogg1GgastIDI2gR98E7VuKD2JqVrARlunfnOIDaj-M", sheet="comunidades") 


inegi.comms <- readr::read_csv(here::here("inputs", "inegi_coast_comm.csv"))


geo.comms <- coms.fish %>% 
  dplyr::left_join(inegi.comms, by = c("NOM_LOC","NOM_ENT"))

geo.sf <- geo.comms %>% 
  sf::st_as_sf(coords = c("deci_lon", "deci_lat"), crs = 4326) 

sf::st_write(geo.sf, here::here("outputs", "goc_fish_comms.shp"), delete_dsn = TRUE)

```

Combine spatial layers for polygon geometry
```{r}

#Natural Protected areas
anp.mex <- sf::st_read(here::here("inputs","shapefiles","232_ANP-ITRF08_04072025.shp"))

#set crs
crs.anp <- sf::st_crs(anp.mex)

#GOC ANPs
goc.anps <- c("Alto Golfo de California y Delta del Río Colorado",
 "Zona marina del Archipiélago de San Lorenzo",
 "Zona marina Bahía de los Ángeles, canales de Ballenas y de Salsipuedes",
 "Balandra",
 "Isla San Pedro Mártir", 
"Islas La Pajarera, Cocinas, Mamut, Colorada, San Pedro, San Agustín, San Andrés y Negrita y los Islotes Los Anegados, Novillas, Mosca y Submarino",
"Cabo Pulmo",
"Bahía de Loreto",
"Cabo San Lucas",
"Islas Marías",
"Islas Marietas",
"Islas del Golfo de California",
"Zona Marina de la Isla Isabel",
"Marismas Nacionales Nayarit",
"El Vizcaíno")
                                                   
#subset only Pacific ANPs and check validity
anp.goc <- anp.mex %>% 
  dplyr::filter(NOMBRE %in% goc.anps) %>% 
   sf::st_make_valid() %>% 
  sf::st_transform(crs=4484)

ggplot2::ggplot(data = anp.goc) +
  ggplot2::geom_sf(ggplot2::aes(fill = NOMBRE)) + # Color areas by a variable
  ggplot2::theme_minimal() 

#get POEM

#read poem
poem.goc <- sf::st_read(here::here("inputs","shapefiles","POEM_GC_2006.shp"))

#transform poem to anp crs and make valid
goc.valid <- sf::st_transform(poem.goc, crs = crs.anp) %>% 
sf::st_make_valid()

#dissolve polygons to get general shape
agg.goc <- rmapshaper::ms_dissolve(goc.valid, field = "FolderPa_1")

#simplify while respecting topology and borders

poem.simpl <- rmapshaper::ms_simplify(agg.goc, keep = 0.001,
                                keep_shapes = FALSE) %>% 
  sf::st_transform(crs=4484)

#save generalized poem as shapefile
sf::st_write(poem.simpl, here::here("outputs","poem_general.shp"), delete_layer = TRUE)


#clip anp layer with general poem
#remove small polygons
clip.anp <- sf::st_intersection(poem.simpl, anp.goc) %>% 
  sf::st_make_valid() %>% 
  dplyr::filter(SUPERFICIE>10000)

#plot both layers to check overlap

over.plot <- ggplot2::ggplot() + 
  ggplot2::geom_sf(data = poem.simpl, color="lightblue") + # 
  ggplot2::geom_sf(data = clip.anp, ggplot2::aes(fill = NOMBRE)) + # Outlines
  ggplot2::theme_bw() # Use a clean theme


#simplify polygons
clip.anp.simpl <- sf::st_simplify(clip.anp, preserveTopology = TRUE,
                        dTolerance = 80) 

over.clip.simpl <- ggplot2::ggplot() + 
  ggplot2::geom_sf(data = poem.simpl, color="lightblue") + # 
  ggplot2::geom_sf(data = clip.anp.simpl , ggplot2::aes(fill = NOMBRE)) + # Outlines
  ggplot2::theme_bw() # Use a clean theme

#simplify while respecting topology and borders
anp.simple <- rmapshaper::ms_simplify(clip.anp.simpl, keep = 0.009, weighting = 0.9,
                                keep_shapes = TRUE) %>% 
  dplyr::mutate(area_sq_m = sf::st_area(geometry),
area_sq_km = units::set_units(area_sq_m, km^2), polygon="anp") %>% 
  dplyr::select(area_sq_km, polygon)

over.plot.simpl <- ggplot2::ggplot() + 
  ggplot2::geom_sf(data = poem.simpl, color="lightblue") + # 
  ggplot2::geom_sf(data = anp.simple, ggplot2::aes(fill = NOMBRE)) + # Outlines
  ggplot2::theme_bw() # Use a clean theme


#add vaquita polygon
vaquita.simple <- sf::st_read(here::here("inputs","shapefiles","Poligono_vaquita_Project.shp"))%>% 
   sf::st_make_valid() %>% 
  sf::st_transform(crs=4484) %>% 
  dplyr::mutate(area_sq_m = sf::st_area(geometry),
area_sq_km = units::set_units(area_sq_m, km^2), polygon="vaquita") %>% 
  dplyr::select(area_sq_km, polygon)


#simplify poem polygons

goc.comb.simp<- goc.valid %>% 
  sf::st_transform(crs=4484) %>% 
#simplify while respecting topology and borders
rmapshaper::ms_simplify(keep =  0.004375,
                                keep_shapes = FALSE)

goc.simple <- goc.comb.simp %>% 
  dplyr::mutate(area_sq_m = sf::st_area(geometry),
area_sq_km = units::set_units(area_sq_m, km^2), polygon="poem") %>% 
  dplyr::select(area_sq_km, polygon)

ggplot2::ggplot() + 
  ggplot2::geom_sf(data = poem.simpl, color="lightblue") + # 
  ggplot2::geom_sf(data = goc.simple, color = "darkblue", alpha = 0.5) + # Outlines
  ggplot2::theme_bw() # Use a clean theme

#add island polygons

#add islands and check validity
islands.pol <- sf::st_read(here::here("inputs","shapefiles","IGolfoCalif.shp"))%>% 
  sf::st_make_valid() %>% 
  sf::st_transform(crs=4484) 

#separate into polygons and leave only large islands
pol.islands <-  islands.pol %>% 
  dplyr::select(NOMBRE) %>% 
  sf::st_cast("POLYGON") %>% 
  dplyr::mutate(area_sq_m = sf::st_area(geometry),
area_sq_km = units::set_units(area_sq_m, km^2)) %>% 
  dplyr::filter(area_sq_km > units::set_units(100, "km^2"))
  
 
#simplify while respecting topology and borders
  islands.simple <-  pol.islands %>% 
    sf::st_buffer(4000, nQuadSegs = 1) %>% 
    sf::st_simplify(preserveTopology = TRUE,
                    dTolerance = 100)  %>% 
     rmapshaper::ms_simplify(keep = 0.035,
                          keep_shapes = FALSE) %>% 
    dplyr::mutate(area_sq_m = sf::st_area(geometry),
area_sq_km = units::set_units(area_sq_m, km^2), polygon="islands") %>% 
  dplyr::select(area_sq_km, polygon)


  goc.areas <- dplyr::bind_rows(anp.simple, vaquita.simple, goc.simple, islands.simple) %>% 
      dplyr::filter(area_sq_km > units::set_units(100, "km^2")) %>% 
     rmapshaper::ms_simplify(keep = 0.75,
                          keep_shapes = FALSE)
    
#plot final polygon

final.pol <- ggplot2::ggplot() + 
#  ggplot2::geom_sf(data = poem.simpl, color="lightblue") + # 
  ggplot2::geom_sf(data = goc.areas, color = "darkblue", alpha = 0.5) + # Outlines
  ggplot2::theme_bw() # Use a clean theme

#save as table
goc.areas %>% sf::st_drop_geometry() %>% readr::write_csv(here::here("outputs",""))

#save as shapefile
sf::st_write(goc.areas, here::here("outputs","goc_model_pol.shp"), delete_layer = TRUE)
```


Import fishery refuge layer and generalize

```{r}
#Fisheries refuges
refuges <- sf::st_read(here::here("inputs","shapefiles","refugios_pesqueros.shp")) %>% 
  sf::st_make_valid() %>% 
  sf::st_transform(crs=4484) 

#read generalized poem
poem.simpl <- sf::st_read(here::here("outputs","poem_general.shp"))

#clip anp layer with general poem
clip.refuges <- sf::st_intersection(poem.simpl, refuges) 

refuges.sim <- rmapshaper::ms_simplify(clip.refuges, keep = 0.5, weighting = 0.9,
                                keep_shapes = TRUE)

#plot final polygon

refuge.plot <- ggplot2::ggplot() + 
  ggplot2::geom_sf(data = refuges.sim, color = "darkblue", alpha = 0.5) + # Outlines
  ggplot2::geom_sf(data = clip.refuges, fill = "lightblue", alpha = 0.5) + # Outlines
  ggplot2::theme_bw() # Use a clean theme

#save as shapefile
sf::st_write(refuges.sim, here::here("outputs","simple_fishery_refuges.shp"), delete_layer = TRUE)

```

Import Ramsar site layer and generalize

```{r}
#Ramsar sites
ramsar.sites <- sf::st_read(here::here("inputs","shapefiles","Sitios_Ramsar.shp")) %>% 
  sf::st_make_valid() %>% 
  sf::st_transform(crs=4484) %>% 
  dplyr::filter(Estado %in% c("Baja California", "Baja California Sur", "Sonora", "Sinaloa", "Nayarit", "Jalisco","Baja California, Sonora","Baja Califonria","Baja California Su","Sinaloa, Nayarit","Sonora-Sinaloa"))

# did not clip by poem so it would keep the coastal sites 

ramsar.sim <- ramsar.sites %>% 
  dplyr::select(Ramsar) %>% 
   sf::st_buffer(500, nQuadSegs = 1) %>% 
    sf::st_simplify(preserveTopology = TRUE,
                    dTolerance = 100) %>% 
  rmapshaper::ms_simplify(keep = 0.25, weighting = 0.9,
                                keep_shapes = TRUE) 
  
  
#plot final polygon

ramsar.plot <- ggplot2::ggplot() + 
  ggplot2::geom_sf(data = ramsar.sim, color = "red", alpha = 0.5) + # Outlines
  ggplot2::geom_sf(data = ramsar.sites, fill = "lightblue", alpha = 0.5) + # Outlines
  ggplot2::theme_bw() # Use a clean theme

#save as shapefile
sf::st_write(ramsar.sim, here::here("outputs","simple_ramsar_all.shp"), delete_layer = TRUE)

```

Read polygons that were edited manually
```{r}

goc.rev <- sf::st_read(here::here("inputs","shapefiles","goc_polygon_final_092526.shp"))

prepare_shapefile(goc.rev)

```

